Repository pocoproject/poco, pull requests merged in 2022-06, with the labels that each got.

#3453 added facility to SyslogChannel
  Foundation/src/SyslogChannel.cpp
Labels: enhancement

#2961 TCPServerDispatcher.h: missing <atomic>
  Net/include/Poco/Net/TCPServerDispatcher.h
Labels: enhancement

#3604 fix(Zip): Zip 64-bit extensions not set #2590
  Zip/include/Poco/Zip/ZipFileInfo.h
  Zip/src/Compress.cpp
  Zip/src/ZipLocalFileHeader.cpp
Labels: pending

#3639 Bugcheck: indicate compiler that functions will never return
  Foundation/include/Poco/Bugcheck.h
Labels: enhancement

#3640 fix warning C4717: 'format<std::vector<std::any,std::allocatorstd::an…
  Foundation/include/Poco/Format.h
Labels: enhancement

#3641 FifoBuffer.advance method not throw exception when length==0
  Foundation/include/Poco/FIFOBuffer.h
Labels: enhancement

#3476 add separate accessors and mutators for connect, send and receive tim…
  Net/include/Poco/Net/HTTPSession.h
Labels: feature
