Repository pocoproject/poco, pull requests merged in 2022-05, with the labels that each got.

#3491 Extract JSON type as string
  Data/MySQL/include/Poco/Data/MySQL/Extractor.h
  Data/MySQL/src/Extractor.cpp
  Data/MySQL/src/ResultMetadata.cpp
  Data/MySQL/testsuite/src/MySQLTest.cpp
  Data/MySQL/testsuite/src/MySQLTest.h
  Data/MySQL/testsuite/src/SQLExecutor.cpp
  Data/MySQL/testsuite/src/SQLExecutor.h
  Data/include/Poco/Data/LOB.h
  Data/include/Poco/Data/MetaColumn.h
  Data/src/RecordSet.cpp
  Data/src/StatementImpl.cpp
Labels: enhancement, feature

#3545 Add --ldflags configure option
  .github/workflows/close-inactive-issues.yml
  README.md
  build/rules/global
  configure
Labels: buildsystem

#3529 Added LocalConfigurationView to only search inside the viewed scope
  Util/Makefile
  Util/Util_vs140.vcxproj
  Util/Util_vs140.vcxproj.filters
  Util/Util_vs150.vcxproj
  Util/Util_vs150.vcxproj.filters
  Util/Util_vs160.vcxproj
  Util/Util_vs160.vcxproj.filters
  Util/Util_vs170.vcxproj
  Util/Util_vs170.vcxproj.filters
  Util/Util_vs90.vcproj
  Util/include/Poco/Util/AbstractConfiguration.h
  Util/include/Poco/Util/LocalConfigurationView.h
  Util/src/AbstractConfiguration.cpp
  Util/src/LocalConfigurationView.cpp
  Util/testsuite/Makefile
  Util/testsuite/TestSuite_vs140.vcxproj
  Util/testsuite/TestSuite_vs140.vcxproj.filters
  Util/testsuite/TestSuite_vs150.vcxproj
  Util/testsuite/TestSuite_vs150.vcxproj.filters
  Util/testsuite/TestSuite_vs160.vcxproj
  Util/testsuite/TestSuite_vs160.vcxproj.filters
  Util/testsuite/TestSuite_vs170.vcxproj
  Util/testsuite/TestSuite_vs170.vcxproj.filters
  Util/testsuite/TestSuite_vs90.vcproj
  Util/testsuite/src/ConfigurationTestSuite.cpp
  Util/testsuite/src/LocalConfigurationViewTest.cpp
  Util/testsuite/src/LocalConfigurationViewTest.h
Labels: feature

#2943 Avoid clang 10 -Wimplicit-int-float-conversion warning/error when con…
  Foundation/include/Poco/Dynamic/VarHolder.h
Labels: enhancement

#3471 #2569: Added TIMESTAMP data type support on MySQL
  Data/MySQL/src/ResultMetadata.cpp
  Data/MySQL/testsuite/src/MySQLTest.cpp
  Data/MySQL/testsuite/src/MySQLTest.h
  Data/MySQL/testsuite/src/SQLExecutor.cpp
  Data/MySQL/testsuite/src/SQLExecutor.h
Labels: feature

#3452 Syslog: Include Facility to Syslog Message
  Net/include/Poco/Net/RemoteSyslogChannel.h
  Net/include/Poco/Net/RemoteSyslogListener.h
  Net/src/RemoteSyslogChannel.cpp
  Net/src/RemoteSyslogListener.cpp
  Net/testsuite/src/SyslogTest.cpp
  Net/testsuite/src/SyslogTest.h
Labels: feature

#3404 Net: make MessageHeader limits configurable
  Net/include/Poco/Net/MessageHeader.h
  Net/src/MessageHeader.cpp
  Net/testsuite/src/MessageHeaderTest.cpp
  Net/testsuite/src/MessageHeaderTest.h
Labels: feature

#3058 Output to stderr in Poco::WindowsConsoleChannel
  Foundation/src/WindowsConsoleChannel.cpp
Labels: enhancement

#3026 HTTPDigestCredentials added support for RFC7616 algorithms
  Foundation/include/Poco/SHA2Engine.h
  Foundation/src/SHA2Engine.cpp
  Foundation/testsuite/src/SHA2EngineTest.cpp
  Foundation/testsuite/src/SHA2EngineTest.h
  Net/include/Poco/Net/HTTPDigestCredentials.h
  Net/src/HTTPDigestCredentials.cpp
  Net/testsuite/src/HTTPCredentialsTest.cpp
  Net/testsuite/src/HTTPCredentialsTest.h
Labels: feature

#3018 Added support for SQLite transaction types using Session property
  Data/SQLite/include/Poco/Data/SQLite/SQLite.h
  Data/SQLite/include/Poco/Data/SQLite/SessionImpl.h
  Data/SQLite/src/SessionImpl.cpp
  Data/SQLite/testsuite/src/SQLiteTest.cpp
  Data/SQLite/testsuite/src/SQLiteTest.h
Labels: feature
