Repository pocoproject/poco, pull requests merged in 2022-07, with the labels that each got.

#2959 Fix percent-encoded fragment modification in Poco::URI
  Foundation/include/Poco/URI.h
  Foundation/src/URI.cpp
  Foundation/testsuite/src/URITest.cpp
Labels: enhancement, pending

#3657 Add lower case format for `NumberFormatter`
  Foundation/include/Poco/NumberFormatter.h
  Foundation/include/Poco/NumericString.h
  Foundation/testsuite/src/NumberFormatterTest.cpp
  Foundation/testsuite/src/StringTest.cpp
Labels: enhancement

#3630 Fix/poll set race
  Net/include/Poco/Net/PollSet.h
  Net/src/PollSet.cpp
  Net/testsuite/Makefile
  Net/testsuite/src/PollSetTest.cpp
  Net/testsuite/src/PollSetTest.h
  Net/testsuite/src/ReactorTestSuite.cpp
  Net/testsuite/src/SocketConnectorTest.cpp
  Net/testsuite/src/SocketConnectorTest.h
Labels: enhancement

#3384 Always set thread names on POSIX platforms
  .gitignore
  Foundation/src/Thread_POSIX.cpp
Labels: platform_specific

#3684 Update Var.h
  Foundation/include/Poco/Dynamic/Var.h
Labels: enhancement

#3664 set thread name
  Foundation/include/Poco/Config.h
  Foundation/include/Poco/Thread.h
  Foundation/include/Poco/Thread_POSIX.h
  Foundation/include/Poco/Thread_VX.h
  Foundation/include/Poco/Thread_WIN32.h
  Foundation/include/Poco/Thread_WINCE.h
  Foundation/src/Thread.cpp
  Foundation/src/Thread_POSIX.cpp
  Foundation/src/Thread_VX.cpp
  Foundation/src/Thread_WIN32.cpp
  Foundation/src/Thread_WINCE.cpp
  Foundation/testsuite/src/ThreadTest.cpp
Labels: enhancement

#3705 Fix/posix sleep
  .vscode/settings.json
  Foundation/include/Poco/Any.h
  Foundation/include/Poco/TaskManager.h
  Foundation/include/Poco/Thread.h
  Foundation/include/Poco/Thread_POSIX.h
  Foundation/include/Poco/Thread_VX.h
  Foundation/include/Poco/Thread_WIN32.h
  Foundation/include/Poco/Thread_WINCE.h
  Foundation/include/Poco/UnWindows.h
  Foundation/src/Task.cpp
  Foundation/src/TaskManager.cpp
  Foundation/src/Thread_POSIX.cpp
  Foundation/src/Thread_VX.cpp
  Foundation/src/Thread_WIN32.cpp
  Foundation/testsuite/src/TaskManagerTest.cpp
  Foundation/testsuite/src/ThreadTest.cpp
  Foundation/testsuite/src/ThreadTest.h
  Net/include/Poco/Net/SocketNotification.h
  Net/include/Poco/Net/SocketReactor.h
  Net/src/PollSet.cpp
  Net/src/SocketNotification.cpp
  Net/src/SocketReactor.cpp
  Net/testsuite/src/PollSetTest.cpp
  Net/testsuite/src/SocketConnectorTest.cpp
  Net/testsuite/src/SocketReactorTest.cpp
  Net/testsuite/src/SocketReactorTest.h
Labels: bug, enhancement

#3720 Update max MSVC version information
  README
Labels: documentation

#3722 Added missing Crypto Header to ProGen source
  Crypto/Crypto_VS90.vcproj
  Crypto/testsuite/TestSuite_VS90.vcproj
Labels: buildsystem
