Repository pocoproject/poco, pull requests merged in 2024-09, with the labels that each got.

#4351 Using native sendfile from OS for HttpServer
  CMakeLists.txt
  Foundation/include/Poco/Config.h
  Foundation/include/Poco/FileStream.h
  Foundation/include/Poco/FileStream_POSIX.h
  Foundation/include/Poco/Types.h
  Net/CMakeLists.txt
  Net/include/Poco/Net/SocketImpl.h
  Net/include/Poco/Net/StreamSocket.h
  Net/src/HTTPServerResponseImpl.cpp
  Net/src/SocketImpl.cpp
  Net/src/StreamSocket.cpp
  Net/testsuite/src/HTTPServerTest.cpp
  Net/testsuite/src/HTTPServerTest.h
  Net/testsuite/src/SocketStreamTest.cpp
  Net/testsuite/src/SocketStreamTest.h
Labels: enhancement, performance

#4677 libpng version 1.6.43
  PDF/CMakeLists.txt
  PDF/include/Poco/PDF/png.h
  PDF/include/Poco/PDF/pngconf.h
  PDF/include/Poco/PDF/pngdebug.h
  PDF/include/Poco/PDF/pnginfo.h
  PDF/include/Poco/PDF/pnglibconf.h
  PDF/include/Poco/PDF/pngpriv.h
  PDF/include/Poco/PDF/pngstruct.h
  PDF/src/png.c
  PDF/src/pngerror.c
  PDF/src/pngget.c
  PDF/src/pngmem.c
  PDF/src/pngpread.c
  PDF/src/pngread.c
  PDF/src/pngrio.c
  PDF/src/pngrtran.c
  PDF/src/pngrutil.c
  PDF/src/pngset.c
  PDF/src/pngtest.c
  PDF/src/pngtrans.c
  PDF/src/pngwio.c
  PDF/src/pngwrite.c
  PDF/src/pngwtran.c
  PDF/src/pngwutil.c
Labels: enhancement, security, third-party

#4681 zlib: Version 1.3.1 in module PDF (#4582)
  Foundation/CMakeLists.txt
  PDF/CMakeLists.txt
  PDF/Makefile
  PDF/PDF_vs160.vcxproj
  PDF/PDF_vs160.vcxproj.filters
  PDF/PDF_vs170.vcxproj
  PDF/PDF_vs170.vcxproj.filters
  PDF/PDF_vs90.vcproj
  PDF/include/Poco/PDF/adler32.c
  PDF/include/Poco/PDF/crc32.h
  PDF/include/Poco/PDF/deflate.h
  PDF/include/Poco/PDF/gzguts.h
  PDF/include/Poco/PDF/inffast.h
  PDF/include/Poco/PDF/inffixed.h
  PDF/include/Poco/PDF/inflate.h
  PDF/include/Poco/PDF/inftrees.h
  PDF/include/Poco/PDF/trees.h
  PDF/include/Poco/PDF/zconf.h
  PDF/include/Poco/PDF/zlib.h
  PDF/include/Poco/PDF/zutil.h
  PDF/src/adler32.c
  PDF/src/compress.c
  PDF/src/crc32.c
  PDF/src/deflate.c
  PDF/src/gzio.c
  PDF/src/infback.c
  PDF/src/inffast.c
  PDF/src/inflate.c
  PDF/src/inftrees.c
  PDF/src/trees.c
  PDF/src/zutil.c
Labels: enhancement, third-party

#4685 CMake: Remove possibility to build with internal OpenSSL
  CMakeLists.txt
  cmake/UseEmbeddedOpenSSL.cmake
Labels: third-party, cmake

#4699 Apply patches from Debian packaging
  Foundation/CMakeLists.txt
  Foundation/testsuite/CMakeLists.txt
Labels: enhancement

#4700 enh(Nullable, Optional): reimplement using std::optional (#4502)
  Data/include/Poco/Data/AbstractBinder.h
  Foundation/include/Poco/Nullable.h
  Foundation/include/Poco/Optional.h
  Foundation/testsuite/src/CoreTest.cpp
Labels: enhancement

#4683 Bundled expat version 2.6.3
  XML/include/Poco/XML/expat.h
  XML/src/siphash.h
  XML/src/xmlparse.cpp
Labels: enhancement, security, third-party

#4715 Add UTF8String::normalize()
  .github/workflows/ci.yml
  Foundation/CMakeLists.txt
  Foundation/Foundation_vs160.vcxproj
  Foundation/Foundation_vs160.vcxproj.filters
  Foundation/Foundation_vs170.vcxproj
  Foundation/Foundation_vs170.vcxproj.filters
  Foundation/Makefile
  Foundation/include/Poco/UTF8String.h
  Foundation/src/UTF8String.cpp
  Foundation/src/utf8proc.c
  Foundation/src/utf8proc.h
  Foundation/src/utf8proc_data.c
  Foundation/testsuite/Makefile-Driver
  Foundation/testsuite/src/UTF8StringTest.cpp
  Foundation/testsuite/src/UTF8StringTest.h
  cmake/FindUtf8Proc.cmake
Labels: feature

#4717 Logging: JSONFormatter
  Foundation/Foundation_vs160.vcxproj
  Foundation/Foundation_vs160.vcxproj.filters
  Foundation/Foundation_vs170.vcxproj
  Foundation/Foundation_vs170.vcxproj.filters
  Foundation/Makefile
  Foundation/include/Poco/JSONFormatter.h
  Foundation/src/JSONFormatter.cpp
  Foundation/src/LoggingFactory.cpp
  Foundation/testsuite/Makefile-Driver
  Foundation/testsuite/TestSuite_vs160.vcxproj
  Foundation/testsuite/TestSuite_vs160.vcxproj.filters
  Foundation/testsuite/TestSuite_vs170.vcxproj
  Foundation/testsuite/TestSuite_vs170.vcxproj.filters
  Foundation/testsuite/src/JSONFormatterTest.cpp
  Foundation/testsuite/src/JSONFormatterTest.h
  Foundation/testsuite/src/LoggingTestSuite.cpp
Labels: feature
