Repository pocoproject/poco, pull requests merged in 2024-10, with the labels that each got.

#4678 pcre2: Version 10.44 (#4478)
  Foundation/CMakeLists.txt
  Foundation/Foundation_vs160.vcxproj
  Foundation/Foundation_vs160.vcxproj.filters
  Foundation/Foundation_vs170.vcxproj
  Foundation/Foundation_vs170.vcxproj.filters
  Foundation/Makefile
  Foundation/src/RegularExpression.cpp
  Foundation/src/Unicode.cpp
  Foundation/src/pcre2.h
  Foundation/src/pcre2_auto_possess.c
  Foundation/src/pcre2_chartables.c
  Foundation/src/pcre2_chkdint.c
  Foundation/src/pcre2_compile.c
  Foundation/src/pcre2_config.h
  Foundation/src/pcre2_context.c
  Foundation/src/pcre2_convert.c
  Foundation/src/pcre2_dfa_match.c
  Foundation/src/pcre2_error.c
  Foundation/src/pcre2_extuni.c
  Foundation/src/pcre2_find_bracket.c
  Foundation/src/pcre2_internal.h
  Foundation/src/pcre2_intmodedep.h
  Foundation/src/pcre2_jit_compile.c
  Foundation/src/pcre2_jit_match.c
  Foundation/src/pcre2_jit_misc.c
  Foundation/src/pcre2_maketables.c
  Foundation/src/pcre2_match.c
  Foundation/src/pcre2_match_data.c
  Foundation/src/pcre2_study.c
  Foundation/src/pcre2_substring.c
  Foundation/src/pcre2_tables.c
  Foundation/src/pcre2_ucd.c
  Foundation/src/pcre2_ucp.h
  Foundation/src/pcre2_ucptables.c
  Foundation/src/pcre2_valid_utf.c
  Foundation/src/pcre2_xclass.c
Labels: enhancement, security, third-party

#4714 Add missing relational operators to VarIterator
  Foundation/include/Poco/Dynamic/VarIterator.h
  Foundation/src/VarIterator.cpp
  Foundation/testsuite/src/VarTest.cpp
Labels: enhancement

#4640 Poco::DateTime uses assertions for validation #1540
  Foundation/include/Poco/DateTime.h
  Foundation/src/DateTime.cpp
  Foundation/testsuite/src/DateTimeTest.cpp
  Foundation/testsuite/src/DateTimeTest.h
Labels: enhancement

#4724 Hide zlib and expat libs from the user of Poco libraries (replaces #4579)
  Foundation/CMakeLists.txt
  Foundation/include/Poco/DeflatingStream.h
  Foundation/include/Poco/InflatingStream.h
  Foundation/src/Checksum.cpp
  Foundation/src/DeflatingStream.cpp
  Foundation/src/InflatingStream.cpp
  Foundation/src/ucp.h
  Foundation/testsuite/src/ZLibTest.cpp
  PocoDoc/cfg/mkdoc-poco.xml
  PocoDoc/cfg/mkdocumentation.xml
  XML/XML_vs90.vcproj
  XML/include/Poco/SAX/SAXParser.h
  XML/include/Poco/XML/XMLStreamParser.h
  XML/src/ParserEngine.cpp
  XML/src/ParserEngine.h
  XML/src/SAXParser.cpp
  XML/src/XMLStreamParser.cpp
  XML/src/expat.h
  XML/src/expat_external.h
  XML/src/internal.h
  XML/src/xmlparse.cpp
  XML/src/xmlrole.c
  XML/src/xmltok.c
  Zip/src/ZipStream.cpp
Labels: enhancement, third-party

#4727 GitHub runner ubuntu 24.04 and resolve some issues
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  CppUnit/src/TestRunner.cpp
  Data/include/Poco/Data/Date.h
  Data/include/Poco/Data/Time.h
  Data/testsuite/src/DataTest.cpp
  Data/testsuite/src/DataTest.h
  Foundation/include/Poco/RotateStrategy.h
  Foundation/src/Path.cpp
  Foundation/testsuite/src/ArrayTest.cpp
  Foundation/testsuite/src/CoreTest.cpp
  Foundation/testsuite/src/DateTimeTest.cpp
  XML/src/XMLStreamParser.cpp
  cmake/DefinePlatformSpecific.cmake
Labels: CI

#4693 Serializable Isolation level for SQLite Databases
  Data/SQLite/include/Poco/Data/SQLite/SessionImpl.h
  Data/SQLite/src/SessionImpl.cpp
  Data/SQLite/testsuite/src/SQLiteTest.cpp
  Data/SQLite/testsuite/src/SQLiteTest.h
Labels: enhancement

#4733 feat(ServerApplication): termination callback #4643
  Util/include/Poco/Util/ServerApplication.h
  Util/src/ServerApplication.cpp
Labels: feature

#4737 fix(cmake): fix Data::PostgreSQL target include, remove unnecessary cmake modules.
  CMakeLists.txt
  Data/PostgreSQL/CMakeLists.txt
  README.md
  cmake/FindODBC.cmake
  cmake/FindPostgreSQL.cmake
  cmake/V313/FindSQLite3.cmake
  cmake/V33/FindOpenSSL.cmake
  cmake/V39/FindEXPAT.cmake
Labels: buildsystem, cmake

#4734 File lock
  Foundation/Foundation_vs160.vcxproj
  Foundation/Foundation_vs170.vcxproj
  Foundation/Makefile
  Foundation/include/Poco/FileStreamRWLock.h
  Foundation/include/Poco/FileStreamRWLock_POSIX.h
  Foundation/include/Poco/FileStreamRWLock_WIN32.h
  Foundation/src/FileStreamRWLock.cpp
  Foundation/src/FileStreamRWLock_POSIX.cpp
  Foundation/src/FileStreamRWLock_WIN32.cpp
  Foundation/testsuite/Makefile-Driver
  Foundation/testsuite/TestSuite_vs160.vcxproj
  Foundation/testsuite/TestSuite_vs160.vcxproj.filters
  Foundation/testsuite/TestSuite_vs170.vcxproj
  Foundation/testsuite/TestSuite_vs170.vcxproj.filters
  Foundation/testsuite/src/FileStreamRWLockTest.cpp
  Foundation/testsuite/src/FileStreamRWLockTest.h
  Foundation/testsuite/src/ProcessesTestSuite.cpp
  Foundation/testsuite/src/TestApp.cpp
Labels: feature

#4738 fix(ODBC): Poco:Data::ODBC - MSSQL (n)varchar(max) length issue #4324
  .github/workflows/ci.yml
  CMakeLists.txt
  Data/DataTest/src/SQLExecutor.cpp
  Data/MySQL/include/Poco/Data/MySQL/SessionImpl.h
  Data/MySQL/src/SessionImpl.cpp
  Data/ODBC/CMakeLists.txt
  Data/ODBC/ODBC.make
  Data/ODBC/ODBC_vs170.vcxproj
  Data/ODBC/include/Poco/Data/ODBC/Binder.h
  Data/ODBC/include/Poco/Data/ODBC/Handle.h
  Data/ODBC/include/Poco/Data/ODBC/ODBC.h
  Data/ODBC/include/Poco/Data/ODBC/SessionImpl.h
  Data/ODBC/include/Poco/Data/ODBC/Utility.h
  Data/ODBC/src/Binder.cpp
  Data/ODBC/src/Connector.cpp
  Data/ODBC/src/Extractor.cpp
  Data/ODBC/src/SessionImpl.cpp
  Data/ODBC/src/Utility.cpp
  Data/ODBC/testsuite/TestSuite_vs170.vcxproj
  Data/ODBC/testsuite/src/ODBCSQLServerTest.cpp
  Data/ODBC/testsuite/src/ODBCSQLServerTest.h
  Data/ODBC/testsuite/src/ODBCTestSuite.cpp
  Data/PostgreSQL/include/Poco/Data/PostgreSQL/SessionImpl.h
  Data/PostgreSQL/src/SessionImpl.cpp
  Data/SQLite/include/Poco/Data/SQLite/SessionImpl.h
  Data/SQLite/src/SessionImpl.cpp
  Data/include/Poco/Data/Session.h
  Data/include/Poco/Data/SessionImpl.h
  Data/src/SessionImpl.cpp
  Data/testsuite/src/DataTest.cpp
  Data/testsuite/src/SessionImpl.cpp
  configure
Labels: enhancement

#4721 fix(Data::ODBC): use connection and login timeouts in ODBC session implementation
  Data/DataTest/src/SQLExecutor.cpp
  Data/MySQL/src/Connector.cpp
  Data/ODBC/include/Poco/Data/ODBC/SessionImpl.h
  Data/ODBC/src/ConnectionHandle.cpp
  Data/ODBC/src/SessionImpl.cpp
  Data/SQLite/src/SessionImpl.cpp
  Data/include/Poco/Data/Session.h
  Data/include/Poco/Data/SessionImpl.h
  Data/src/PooledSessionImpl.cpp
  Data/src/SQLChannel.cpp
  Data/src/Session.cpp
  Data/src/SessionFactory.cpp
  Data/src/SessionImpl.cpp
Labels: enhancement

#4748 Activity now sets _running flag to false when it finishes or throws.
  Foundation/include/Poco/Activity.h
  Foundation/testsuite/src/ActivityTest.cpp
  Foundation/testsuite/src/ActivityTest.h
Labels: enhancement
