Repository pocoproject/poco, pull requests merged in 2024-11, with the labels that each got.

#4494 PocoDoc: search support
  CMakeLists.txt
  Data/SQLite/SQLite.progen
  Data/SQLite/SQLite_vs160.vcxproj
  Data/SQLite/SQLite_vs160.vcxproj.filters
  Data/SQLite/SQLite_vs170.vcxproj
  Data/SQLite/SQLite_vs170.vcxproj.filters
  Data/SQLite/testsuite/src/SQLiteTest.cpp
  Data/SQLite/testsuite/src/SQLiteTest.h
  PocoDoc/CMakeLists.txt
  PocoDoc/Makefile
  PocoDoc/PocoDoc_vs160.vcxproj
  PocoDoc/PocoDoc_vs160.vcxproj.filters
  PocoDoc/PocoDoc_vs170.vcxproj
  PocoDoc/PocoDoc_vs170.vcxproj.filters
  PocoDoc/PocoDoc_vs90.vcproj
  PocoDoc/src/DocWriter.cpp
  PocoDoc/src/DocWriter.h
  PocoDoc/src/PocoDoc.cpp
  ProGen/ProGen_vs170.vcxproj
  configure
Labels: enhancement

#4755 Insert NULL using BULK #4001
  Data/DataTest/include/Poco/Data/Test/SQLExecutor.h
  Data/DataTest/src/SQLExecutor.cpp
  Data/MySQL/include/Poco/Data/MySQL/Extractor.h
  Data/MySQL/src/Extractor.cpp
  Data/ODBC/include/Poco/Data/ODBC/Binder.h
  Data/ODBC/include/Poco/Data/ODBC/Extractor.h
  Data/ODBC/include/Poco/Data/ODBC/Preparator.h
  Data/ODBC/include/Poco/Data/ODBC/TypeInfo.h
  Data/ODBC/include/Poco/Data/ODBC/Utility.h
  Data/ODBC/src/Binder.cpp
  Data/ODBC/src/Extractor.cpp
  Data/ODBC/src/ODBCStatementImpl.cpp
  Data/ODBC/src/TypeInfo.cpp
  Data/ODBC/src/Utility.cpp
  Data/ODBC/testsuite/src/ODBCOracleTest.cpp
  Data/ODBC/testsuite/src/ODBCSQLServerTest.cpp
  Data/ODBC/testsuite/src/ODBCSQLServerTest.h
  Data/ODBC/testsuite/src/ODBCTest.cpp
  Data/ODBC/testsuite/src/ODBCTest.h
  Data/ODBC/testsuite/src/ODBCTestSuite.cpp
  Data/ODBC/testsuite/src/SQLExecutor.h
  Data/PostgreSQL/include/Poco/Data/PostgreSQL/BinaryExtractor.h
  Data/PostgreSQL/include/Poco/Data/PostgreSQL/Extractor.h
  Data/PostgreSQL/src/BinaryExtractor.cpp
  Data/PostgreSQL/src/Extractor.cpp
  Data/PostgreSQL/testsuite/src/PostgreSQLTest.cpp
  Data/SQLite/include/Poco/Data/SQLite/Extractor.h
  Data/SQLite/src/Extractor.cpp
  Data/SQLite/testsuite/src/SQLiteTest.cpp
  Data/SQLite/testsuite/src/SQLiteTest.h
  Data/include/Poco/Data/AbstractBinder.h
  Data/include/Poco/Data/AbstractExtractor.h
  Data/include/Poco/Data/AbstractPreparator.h
  Data/include/Poco/Data/TypeHandler.h
  Data/src/AbstractExtractor.cpp
  Data/src/AbstractPreparator.cpp
  Data/testsuite/src/DataTest.cpp
  Data/testsuite/src/DataTest.h
  Data/testsuite/src/Extractor.cpp
  Data/testsuite/src/Extractor.h
  Foundation/include/Poco/Exception.h
  Foundation/include/Poco/Nullable.h
  Foundation/include/Poco/Types.h
Labels: enhancement, feature

#4762 Properly define POCO_DLL and POCO_STATIC based on BUILD_SHARED_LIBS
  CppUnit/CMakeLists.txt
  DNSSD/CMakeLists.txt
  Foundation/CMakeLists.txt
  build_cmake.sh
  cmake/DefinePlatformSpecific.cmake
Labels: cmake

#4774 Non-blocking sockets support (TLS, WebSocket)
  Net/include/Poco/Net/WebSocket.h
  Net/include/Poco/Net/WebSocketImpl.h
  Net/src/SocketImpl.cpp
  Net/src/StreamSocketImpl.cpp
  Net/src/WebSocket.cpp
  Net/src/WebSocketImpl.cpp
  Net/testsuite/src/SocketTest.cpp
  Net/testsuite/src/SocketTest.h
  Net/testsuite/src/WebSocketTest.cpp
  Net/testsuite/src/WebSocketTest.h
  NetSSL_OpenSSL/include/Poco/Net/SecureSocketImpl.h
  NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocketImpl.h
  NetSSL_OpenSSL/src/SecureSocketImpl.cpp
  NetSSL_OpenSSL/src/SecureStreamSocketImpl.cpp
  NetSSL_OpenSSL/testsuite/Makefile
  NetSSL_OpenSSL/testsuite/TestSuite_vs160.vcxproj
  NetSSL_OpenSSL/testsuite/TestSuite_vs160.vcxproj.filters
  NetSSL_OpenSSL/testsuite/TestSuite_vs170.vcxproj
  NetSSL_OpenSSL/testsuite/TestSuite_vs170.vcxproj.filters
  NetSSL_OpenSSL/testsuite/TestSuite_vs90.vcproj
  NetSSL_OpenSSL/testsuite/src/NetSSLTestSuite.cpp
  NetSSL_OpenSSL/testsuite/src/SecureStreamSocketTest.cpp
  NetSSL_OpenSSL/testsuite/src/SecureStreamSocketTest.h
  NetSSL_OpenSSL/testsuite/src/SecureStreamSocketTestSuite.cpp
  NetSSL_OpenSSL/testsuite/src/SecureStreamSocketTestSuite.h
  NetSSL_OpenSSL/testsuite/src/WebSocketTest.cpp
  NetSSL_OpenSSL/testsuite/src/WebSocketTest.h
  NetSSL_Win/include/Poco/Net/SecureSocketImpl.h
  NetSSL_Win/include/Poco/Net/SecureStreamSocketImpl.h
  NetSSL_Win/src/SecureSocketImpl.cpp
  NetSSL_Win/src/SecureStreamSocketImpl.cpp
  NetSSL_Win/testsuite/TestSuite_vs160.vcxproj
  NetSSL_Win/testsuite/TestSuite_vs160.vcxproj.filters
  NetSSL_Win/testsuite/TestSuite_vs170.vcxproj
  NetSSL_Win/testsuite/TestSuite_vs170.vcxproj.filters
  NetSSL_Win/testsuite/TestSuite_vs90.vcproj
  NetSSL_Win/testsuite/src/HTTPSClientSessionTest.cpp
  NetSSL_Win/testsuite/src/NetSSLTestSuite.cpp
  NetSSL_Win/testsuite/src/SecureStreamSocketTest.cpp
  NetSSL_Win/testsuite/src/SecureStreamSocketTest.h
  NetSSL_Win/testsuite/src/SecureStreamSocketTestSuite.cpp
  NetSSL_Win/testsuite/src/SecureStreamSocketTestSuite.h
  NetSSL_Win/testsuite/src/WebSocketTest.cpp
  NetSSL_Win/testsuite/src/WebSocketTestSuite.cpp
  NetSSL_Win/testsuite/src/WebSocketTestSuite.h
Labels: bug, enhancement

#4770 feat(WindowsBuild): customizable path to include for pocoNetworkInitializer #4769
  Net/include/Poco/Net/Net.h
Labels: enhancement

#4777 enh(ODBC): ODBC: DataFormatException getting Time value from SQL Serv…
  Data/ODBC/src/ODBCMetaColumn.cpp
  Data/ODBC/testsuite/src/ODBCSQLServerTest.cpp
  Data/ODBC/testsuite/src/ODBCSQLServerTest.h
Labels: enhancement

#4787 NetSSL_OpenSSL and NetSSL_Win: non-blocking support, shutdown behavior fix
  Net/include/Poco/Net/SocketImpl.h
  Net/include/Poco/Net/StreamSocket.h
  Net/include/Poco/Net/WebSocketImpl.h
  Net/samples/HTTPTimeServer/src/HTTPTimeServer.cpp
  Net/src/SocketImpl.cpp
  Net/src/StreamSocket.cpp
  Net/src/WebSocketImpl.cpp
  NetSSL_OpenSSL/include/Poco/Net/SecureSocketImpl.h
  NetSSL_OpenSSL/include/Poco/Net/SecureStreamSocketImpl.h
  NetSSL_OpenSSL/src/SecureSocketImpl.cpp
  NetSSL_OpenSSL/src/SecureStreamSocketImpl.cpp
  NetSSL_Win/include/Poco/Net/SecureSocketImpl.h
  NetSSL_Win/include/Poco/Net/SecureStreamSocketImpl.h
  NetSSL_Win/include/Poco/Net/Utility.h
  NetSSL_Win/src/HTTPSStreamFactory.cpp
  NetSSL_Win/src/SecureSocketImpl.cpp
  NetSSL_Win/src/SecureStreamSocketImpl.cpp
  NetSSL_Win/src/Utility.cpp
Labels: bug, feature
